-- MySQL Script generated by MySQL Workbench
-- 07/12/17 02:02:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shopping-assistant-db
-- -----------------------------------------------------
-- This database characterises items stocked by vendors and the possible operations on those items, by either consumers or the vendors.
DROP SCHEMA IF EXISTS `shopping-assistant-db` ;

-- -----------------------------------------------------
-- Schema shopping-assistant-db
--
-- This database characterises items stocked by vendors and the possible operations on those items, by either consumers or the vendors.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping-assistant-db` DEFAULT CHARACTER SET utf8 ;
USE `shopping-assistant-db` ;

-- -----------------------------------------------------
-- Table `tbl_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_items` ;

CREATE TABLE IF NOT EXISTS `tbl_items` (
  `itm_id` INT NOT NULL AUTO_INCREMENT,
  `itm_name` VARCHAR(45) NOT NULL COMMENT 'The item name.',
  `itm_unit` VARCHAR(45) NOT NULL DEFAULT 'piece' COMMENT 'Specified sales  unit for the item.',
  `itm_vendor` VARCHAR(45) NOT NULL COMMENT 'An item must have a unique vendor.',
  `itm_category` VARCHAR(45) NOT NULL DEFAULT 'all' COMMENT 'An item must belong to at least one category.',
  `itm_brand` VARCHAR(45) NULL COMMENT 'The brand.',
  `itm_isAvailable` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Shows whether or not the item is available from the vendor.',
  `itm_date_added` TIMESTAMP(12) NOT NULL COMMENT 'When the vendor added the item.',
  `itm_available_quantity` VARCHAR(45) NULL,
  `itm_offers` VARCHAR(45) NULL,
  `itm_image` BLOB NULL COMMENT 'Image of the item.',
  PRIMARY KEY (`itm_id`),
  UNIQUE INDEX `itm_id_UNIQUE` (`itm_id` ASC),
  UNIQUE INDEX `itm_vendor_UNIQUE` (`itm_vendor` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
